#!/usr/bin/with-contenv bash
set -e

vecho () { if [ "${S6_VERBOSITY:-1}" -gt 0 ]; then echo "[$0] $@"; fi; }
if [ "X${EUID}" != "X0" ]; then vecho "Skipped. Reason: no root privileges."; exit 0; fi;

vecho "Add ${S6_USER:-alpine} to group: video";

if [ -n "${GID_VIDEO}" ]; # update gid of 'video' if defined
then
    groupmod -o -g "${GID_VIDEO}" video;
fi

adduser ${S6_USER:-alpine} video;

USERHOMEDIR="$(getent passwd ${S6_USER:-alpine} | cut -d: -f6)";
GIMPVERSION="$(gimp --version|grep 'GNU Image Manipulation Program version'| awk '{print $6}')";

# ensure gimp dirs
# previously configs were in "${USERHOMEDIR}/.gimp-${GIMPVERSION%\.*}"
vecho "Ensure configuration directories exist.";
mkdir -p \
    "${USERHOMEDIR}/Pictures" \
    "${USERHOMEDIR}/.config/GIMP/${GIMPVERSION%\.*}" \
    "${USERHOMEDIR}/.local" \
    ;

# fix permissions
vecho "Fixing permissions.";
chown ${S6_USER:-alpine}:${PGID:-1000} \
    "${USERHOMEDIR}" \
    "${USERHOMEDIR}/Pictures" \
    ;

chown -R ${S6_USER:-alpine}:${PGID:-1000} \
    "${USERHOMEDIR}/.config/GIMP/${GIMPVERSION%\.*}" \
    "${USERHOMEDIR}/.local" \
    ;
